# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/detailed_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DetailedWindow(object):
    def setupUi(self, DetailedWindow):
        DetailedWindow.setObjectName("DetailedWindow")
        DetailedWindow.resize(800, 600)
        self.tableWidget = QtWidgets.QTableWidget(DetailedWindow)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 780, 580))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")

        self.retranslateUi(DetailedWindow)
        QtCore.QMetaObject.connectSlotsByName(DetailedWindow)

    def retranslateUi(self, DetailedWindow):
        _translate = QtCore.QCoreApplication.translate
        DetailedWindow.setWindowTitle(_translate("DetailedWindow", "Детальный просмотр"))
